#Requires -Version 5.1
<#
.SYNOPSIS
Generates NSIS and WiX prerequisite metadata from the pinned Microsoft x64 runtime.
.DESCRIPTION
No Microsoft download, installer execution, or CRT staging occurs during
preparation. Both include files use the same validated pin. The free InetC NSIS
HTTPS plugin is checksum-pinned separately and cached with its license notice.
#>
[CmdletBinding()]
param(
    [string]$ManifestPath = (Join-Path $PSScriptRoot 'windows-runtime.json'),
    [string]$OutputDirectory = (Join-Path $PSScriptRoot '../src-tauri/windows-resources')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'windows-runtime-common.ps1')

if ($env:TAURI_ENV_ARCH -and $env:TAURI_ENV_ARCH -notin @('x86_64', 'x64')) {
    throw "The Windows runtime prerequisite supports x64 only, not TAURI_ENV_ARCH=$env:TAURI_ENV_ARCH"
}
foreach ($variable in @('CARGO_BUILD_TARGET', 'DF_BUILD_TARGET_TRIPLE')) {
    $target = [Environment]::GetEnvironmentVariable($variable)
    if ($target -and $target -ne 'x86_64-pc-windows-msvc') {
        throw "The Windows runtime prerequisite requires x86_64-pc-windows-msvc, not ${variable}=$target"
    }
}

$pin = Read-DfVcManifest $ManifestPath
$version = ConvertTo-DfVcVersion $pin.version
if ([Environment]::OSVersion.Platform -eq [PlatformID]::Win32NT) {
    # MSVC's newer headers can require a newer runtime even when DLL names match.
    $vswhere = Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio/Installer/vswhere.exe'
    if (-not (Test-Path -LiteralPath $vswhere -PathType Leaf)) {
        throw 'vswhere.exe is missing; install the Visual Studio C++ x64 build tools.'
    }
    $vcvars = @(& $vswhere -latest -products '*' -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -find 'VC\Auxiliary\Build\vcvars64.bat')
    if ($LASTEXITCODE -ne 0 -or $vcvars.Count -ne 1) {
        throw 'Could not locate exactly one vcvars64.bat for the latest installed C++ toolset.'
    }
    $command = '""{0}" >nul && set VCToolsRedistDir"' -f $vcvars[0]
    $environment = @(& $env:ComSpec /d /s /c $command)
    if ($LASTEXITCODE -ne 0) { throw "Could not read the selected MSVC environment (exit $LASTEXITCODE)." }
    $redistLine = @($environment | Where-Object { $_.StartsWith('VCToolsRedistDir=', [StringComparison]::OrdinalIgnoreCase) })
    if ($redistLine.Count -ne 1) { throw 'The selected MSVC toolset did not report VCToolsRedistDir.' }
    $redistRoot = $redistLine[0].Substring('VCToolsRedistDir='.Length)
    $toolsetRuntime = @(Get-ChildItem -Path (Join-Path $redistRoot 'x64/Microsoft.VC*.CRT/msvcp140.dll') -File)
    if ($toolsetRuntime.Count -ne 1) { throw 'Could not identify the selected toolset x64 redistributable.' }
    $requiredVersion = Get-DfVcBinaryVersion $toolsetRuntime[0].FullName
    if ($version -lt $requiredVersion) {
        throw "Pinned runtime $version is older than the selected MSVC redistributable $requiredVersion. Update the pin before bundling."
    }
    Write-Host "[windows-runtime] Selected toolset CRT $requiredVersion; required system runtime $version."
}
$constants = [ordered]@{
    DF_VC_VERSION = $version.ToString()
    DF_VC_MAJOR = $version.Major
    DF_VC_MINOR = $version.Minor
    DF_VC_BUILD = $version.Build
    DF_VC_REVISION = $version.Revision
    DF_VC_URL = ([uri]$pin.url).AbsoluteUri
    DF_VC_SHA256 = $pin.sha256.ToUpperInvariant()
}
$nsis = @('; Generated by scripts/prepare-windows-runtime.ps1; do not edit.')
$wix = @('<?xml version="1.0" encoding="utf-8"?>', '<Include xmlns="http://schemas.microsoft.com/wix/2006/wi">')
foreach ($entry in $constants.GetEnumerator()) {
    # Validation restricts all values to safe version, hash, and immutable URL text.
    $nsis += '!define {0} "{1}"' -f $entry.Key, $entry.Value
    $wix += '  <?define {0}="{1}" ?>' -f $entry.Key, $entry.Value
}
$wix += '</Include>'
$OutputDirectory = [System.IO.Path]::GetFullPath($OutputDirectory)
[void](New-Item -ItemType Directory -Path $OutputDirectory -Force)
$encoding = [System.Text.UTF8Encoding]::new($false)

$pluginPin = Get-Content -LiteralPath (Join-Path $PSScriptRoot 'windows-runtime-download-plugin.json') -Raw | ConvertFrom-Json
if ($pluginPin.version -notmatch '^\d+\.\d+\.\d+\.\d+\z' -or
    $pluginPin.url -cne "https://github.com/DigitalMediaServer/NSIS-INetC-plugin/releases/download/v$($pluginPin.version)/InetC.zip" -or
    $pluginPin.licenseUrl -cne "https://raw.githubusercontent.com/DigitalMediaServer/NSIS-INetC-plugin/v$($pluginPin.version)/LICENSE.md") {
    throw 'The InetC plugin pin must identify an official tagged release and its license.'
}
foreach ($hash in @($pluginPin.sha256, $pluginPin.pluginSha256, $pluginPin.licenseSha256)) {
    if ($hash -notmatch '^[0-9a-fA-F]{64}\z') { throw 'The InetC plugin pin contains an invalid SHA-256 hash.' }
}
# Normalize checkout line endings to reproduce the exact tagged upstream notice.
$license = [System.IO.File]::ReadAllText((Join-Path $PSScriptRoot 'inetc-license.txt')).Replace("`r`n", "`n")
$sha256 = [System.Security.Cryptography.SHA256]::Create()
try {
    $licenseHash = [BitConverter]::ToString($sha256.ComputeHash($encoding.GetBytes($license))).Replace('-', '')
} finally {
    $sha256.Dispose()
}
if ($licenseHash -ne $pluginPin.licenseSha256) { throw 'The InetC license notice differs from the pinned upstream notice.' }
$pluginDirectory = Join-Path $OutputDirectory 'nsis-plugins'
$pluginPath = Join-Path $pluginDirectory 'x86-unicode/INetC.dll'
$pluginValid = (Test-Path -LiteralPath $pluginPath -PathType Leaf) -and
    ((Get-FileHash -LiteralPath $pluginPath -Algorithm SHA256).Hash -eq $pluginPin.pluginSha256)
if (-not $pluginValid) {
    $work = Join-Path ([System.IO.Path]::GetTempPath()) ('dragonfruit-inetc-' + [guid]::NewGuid().ToString('N'))
    [void](New-Item -ItemType Directory -Path $work)
    try {
        [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
        $archivePath = Join-Path $work 'InetC.zip'
        Invoke-WebRequest -UseBasicParsing -Uri $pluginPin.url -OutFile $archivePath
        if ((Get-FileHash -LiteralPath $archivePath -Algorithm SHA256).Hash -ne $pluginPin.sha256) {
            throw 'The downloaded InetC archive does not match its pinned SHA-256.'
        }
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        $archive = [System.IO.Compression.ZipFile]::OpenRead($archivePath)
        $candidatePath = Join-Path $work 'INetC.dll'
        try {
            $entry = $archive.GetEntry('x86-unicode/INetC.dll')
            if ($null -eq $entry) { throw 'The pinned InetC archive has no x86-Unicode plugin.' }
            [System.IO.Compression.ZipFileExtensions]::ExtractToFile($entry, $candidatePath)
        } finally {
            $archive.Dispose()
        }
        if ((Get-FileHash -LiteralPath $candidatePath -Algorithm SHA256).Hash -ne $pluginPin.pluginSha256) {
            throw 'The extracted InetC plugin does not match its pinned SHA-256.'
        }
        [void](New-Item -ItemType Directory -Path (Split-Path -Parent $pluginPath) -Force)
        Copy-Item -LiteralPath $candidatePath -Destination $pluginPath -Force
    } finally {
        Remove-Item -LiteralPath $work -Recurse -Force
    }
}
[System.IO.File]::WriteAllText((Join-Path $pluginDirectory 'LICENSE.txt'), $license, $encoding)
Write-Host "Prepared checksum-pinned InetC $($pluginPin.version) HTTPS plugin and license notice."

[System.IO.File]::WriteAllText((Join-Path $OutputDirectory 'runtime-version.nsh'), (($nsis -join "`n") + "`n"), $encoding)
[System.IO.File]::WriteAllText((Join-Path $OutputDirectory 'runtime-version.wxi'), (($wix -join "`n") + "`n"), $encoding)
Write-Host "Generated x64 runtime prerequisite metadata for $version in $OutputDirectory (no Microsoft payload downloaded)."
